# =====================================================================
# build_animations.ps1 — converts animated GIFs into PROGMEM frame arrays
# for the Dews Feed pixel-art slide.
#
# THE PIPELINE: drop any .gif into tools\gifs\ and run this script. Each
# GIF is decoded with .NET System.Drawing (built into Windows), scaled to
# fit the 128x64 panel with crisp nearest-neighbor sampling, quantized to
# RGB565, and emitted into ..\pixel_anims.h. The .ino plays whatever is
# compiled in — no code changes needed per animation.
#
# Sources for good matrix GIFs (32x32..64x64 pixel art works best):
#   * SmartMatrix community shares: community.pixelmatix.com/c/animated-gifs
#   * pixelmatix/AnimatedGIFs repo: extras/gifs (7 starter clips)
#   * Giphy/Tenor searches for "pixel art" — anything downloads as .gif
#   * itch.io CC0 sprite/effect packs (export as gif)
#
# FLASH BUDGET: each animation costs W x H x 2 bytes x frames. A 64x64
# GIF at 16 frames = 131 KB. The sketch has roughly 800 KB of headroom on
# the Huge APP partition — the script prints per-file and total cost and
# refuses to emit past the budget cap below.
#
# Run:
#     powershell -ExecutionPolicy Bypass -File .\build_animations.ps1
# =====================================================================

Add-Type -AssemblyName System.Drawing

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$GifDir    = Join-Path $ScriptDir "gifs"
$OutPath   = Join-Path (Split-Path -Parent $ScriptDir) "pixel_anims.h"

$MaxFrames    = 12         # cap frames per animation (evenly sampled if more)
                           # COVER mode makes every frame a full 128x64
                           # (16 KB) — 12 frames = 192 KB per animation,
                           # so 3 animations + a still fit the budget
$MaxW         = 128
$MaxH         = 64
$BudgetKB     = 650        # total flash budget for ALL animations
$DefaultDelay = 100        # ms per frame when the GIF doesn't specify

if (-not (Test-Path $GifDir)) { New-Item -ItemType Directory -Path $GifDir | Out-Null }

# GIFs animate; PNG/JPG stills become single-frame "art cards" — nice for
# detailed pixel-art scenes that don't need motion.
$gifs = @(Get-ChildItem -Path (Join-Path $GifDir '*') -Include *.gif,*.png,*.jpg,*.jpeg | Sort-Object Name)
if ($gifs.Count -eq 0) {
    Write-Host "No GIFs found in $GifDir"
    Write-Host ""
    Write-Host "Drop .gif files there and re-run. Good sources:"
    Write-Host "  - https://community.pixelmatix.com/c/animated-gifs (matrix-tested shares)"
    Write-Host "  - https://github.com/pixelmatix/AnimatedGIFs -> extras/gifs (starters)"
    Write-Host "  - Giphy/Tenor 'pixel art' searches"
    Write-Host ""
    Write-Host "Best results: 32x32 to 64x64 pixel-art GIFs, short loops (<=20 frames)."
    exit 0
}

function ConvertTo-Rgb565([int]$r, [int]$g, [int]$b) {
    $v = ((($r -band 0xF8) -shl 8) -bor (($g -band 0xFC) -shl 3) -bor ($b -shr 3))
    if ($v -eq 0x0001) { $v = 0x0002 }   # avoid transparency sentinel
    return $v
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by tools/build_animations.ps1 - do not edit by hand.")
[void]$sb.AppendLine("// Source GIFs live in tools/gifs/. Re-run the script after changing them.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <Arduino.h>")
[void]$sb.AppendLine("#include <pgmspace.h>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("struct PixelAnim {")
[void]$sb.AppendLine("  const char* name;")
[void]$sb.AppendLine("  uint16_t w, h;")
[void]$sb.AppendLine("  uint8_t  frameCount;")
[void]$sb.AppendLine("  uint16_t delayMs;")
[void]$sb.AppendLine("  const uint16_t* const* frames;")
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")

$index = New-Object 'System.Collections.Generic.List[object]'
$totalBytes = 0

foreach ($gf in $gifs) {
    Write-Host "== $($gf.Name) =="
    try {
        $img = [System.Drawing.Image]::FromFile($gf.FullName)
    } catch {
        Write-Host "  ! failed to open, skipping"
        continue
    }
    $dim = New-Object System.Drawing.Imaging.FrameDimension($img.FrameDimensionsList[0])
    $nSrc = $img.GetFrameCount($dim)

    # Per-frame delays (property 0x5100: 4 bytes/frame in 1/100 sec)
    $delayMs = $DefaultDelay
    try {
        $pd = $img.GetPropertyItem(0x5100).Value
        $d0 = [BitConverter]::ToInt32($pd, 0) * 10
        if ($d0 -ge 20 -and $d0 -le 1000) { $delayMs = $d0 }
    } catch {}

    # Evenly sample frames down to the cap
    $take = [Math]::Min($nSrc, $MaxFrames)
    $frameIdx = @()
    for ($i = 0; $i -lt $take; $i++) { $frameIdx += [int][Math]::Floor($i * $nSrc / $take) }

    # COVER scaling — fill the ENTIRE 128x64 panel. Scale so both axes reach
    # the panel edge, then center-crop the overflow (top/bottom on wide-ish
    # sources, left/right on tall ones). No black bars, per user request.
    $scale = [Math]::Max($MaxW / $img.Width, $MaxH / $img.Height)
    $w = $MaxW
    $h = $MaxH
    $drawW = [int][Math]::Ceiling($img.Width  * $scale)
    $drawH = [int][Math]::Ceiling($img.Height * $scale)
    $offX  = [int](($MaxW - $drawW) / 2)   # <= 0: crop equally each side
    $offY  = [int](($MaxH - $drawH) / 2)

    # Decide interpolation ONCE per file. Blocky sources (true pixel art or
    # pixelit output at full size) have long runs of identical neighboring
    # pixels — those need NearestNeighbor so the blocks stay crisp through
    # the downscale. Photographic sources get bicubic to avoid alias noise.
    $useNN = ($img.Width -le 160 -and $img.Height -le 160)
    if (-not $useNN) {
        $probe = New-Object System.Drawing.Bitmap($img)
        $same = 0; $tot = 0
        $stepX = [Math]::Max(1, [int]($probe.Width / 40))
        $stepY = [Math]::Max(1, [int]($probe.Height / 30))
        for ($py = 0; $py -lt $probe.Height; $py += $stepY) {
            for ($px = 0; $px -lt ($probe.Width - 1); $px += $stepX) {
                $c1 = $probe.GetPixel($px, $py)
                $c2 = $probe.GetPixel($px + 1, $py)
                if ($c1.ToArgb() -eq $c2.ToArgb()) { $same++ }
                $tot++
            }
        }
        $probe.Dispose()
        if ($tot -gt 0 -and ($same / $tot) -ge 0.5) { $useNN = $true }
        $modeTxt = if ($useNN) { "NearestNeighbor (blocky art)" } else { "Bicubic (photographic)" }
        Write-Host ("  neighbor-match {0:P0} -> {1}" -f ($same / [Math]::Max(1,$tot)), $modeTxt)
    }

    $cost = $w * $h * 2 * $take
    if ((($totalBytes + $cost) / 1024) -gt $BudgetKB) {
        Write-Host ("  ! skipping - would exceed {0} KB budget (this file needs {1:N0} KB)" -f $BudgetKB, ($cost/1024))
        $img.Dispose()
        continue
    }
    $totalBytes += $cost

    $safe = ($gf.BaseName.ToUpper() -replace '[^A-Z0-9]', '_')
    $fnames = @()
    $fi = 0
    foreach ($srcIdx in $frameIdx) {
        [void]$img.SelectActiveFrame($dim, $srcIdx)
        $bmp = New-Object System.Drawing.Bitmap $w, $h
        $gfx = [System.Drawing.Graphics]::FromImage($bmp)
        # Interpolation chosen once per file by the blockiness probe above.
        if ($useNN) {
            $gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::NearestNeighbor
        } else {
            $gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        }
        $gfx.PixelOffsetMode   = [System.Drawing.Drawing2D.PixelOffsetMode]::Half
        $gfx.Clear([System.Drawing.Color]::Black)
        # Cover draw: oversized image drawn at negative offset = center crop
        $gfx.DrawImage($img, $offX, $offY, $drawW, $drawH)
        $gfx.Dispose()

        $name = "ANIM_${safe}_F${fi}"
        $fnames += $name
        [void]$sb.Append("const uint16_t $name[$($w*$h)] PROGMEM = {")
        [void]$sb.AppendLine()
        [void]$sb.Append("  ")
        $count = 0
        for ($y = 0; $y -lt $h; $y++) {
            for ($x = 0; $x -lt $w; $x++) {
                $c = $bmp.GetPixel($x, $y)
                $v = if ($c.A -lt 128) { 0x0000 } else { ConvertTo-Rgb565 $c.R $c.G $c.B }
                [void]$sb.Append(("0x{0:X4}" -f $v))
                $count++
                if ($count -ne $w*$h) {
                    [void]$sb.Append(",")
                    if (($count % $w) -eq 0) { [void]$sb.AppendLine(); [void]$sb.Append("  ") }
                    else { [void]$sb.Append(" ") }
                }
            }
        }
        [void]$sb.AppendLine()
        [void]$sb.AppendLine("};")
        $bmp.Dispose()
        $fi++
    }
    $img.Dispose()

    # Frame pointer table
    [void]$sb.AppendLine("const uint16_t* const ANIM_${safe}_FRAMES[$take] PROGMEM = {")
    [void]$sb.AppendLine("  " + ($fnames -join ", "))
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")

    $index.Add(@{ Safe=$safe; Name=$gf.BaseName; W=$w; H=$h; N=$take; D=$delayMs }) | Out-Null
    Write-Host ("  ok  {0}x{1}, {2} frames @ {3}ms  ({4:N0} KB)" -f $w, $h, $take, $delayMs, ($cost/1024))
}

[void]$sb.AppendLine(("const int PIXEL_ANIM_COUNT = {0};" -f $index.Count))
[void]$sb.AppendLine("const PixelAnim PIXEL_ANIMS[] = {")
foreach ($e in $index) {
    [void]$sb.AppendLine(('  {{ "{0}", {1}, {2}, {3}, {4}, ANIM_{5}_FRAMES }},' -f $e.Name, $e.W, $e.H, $e.N, $e.D, $e.Safe))
}
[void]$sb.AppendLine("};")

[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host ""
Write-Host ("Wrote {0} animations, total {1:N0} KB flash -> {2}" -f $index.Count, ($totalBytes/1024), $OutPath)
Write-Host "Now re-flash the .ino from the Arduino IDE."
