# =====================================================================
# build_airline_logos.ps1 — downloads airline logos by ICAO code from
# sexym0nk3y/airline-logos and emits ../airline_logos.h.
#
# Same shape as build_team_logos.ps1 — uses .NET System.Drawing built into
# Windows, so no Python / pip needed. Just:
#     powershell -ExecutionPolicy Bypass -File .\build_airline_logos.ps1
# =====================================================================

Add-Type -AssemblyName System.Drawing

# ICAO codes for the airlines the .ino's airlineFromCallsign() recognizes.
# Add more here as you find new callsign prefixes over Stamford.
$Airlines = @(
    "AAL","UAL","DAL","JBU","SWA","ASA","FFT","NKS","RPA","SKW",
    "EJA","GTI","FDX","UPS","ACA","JZA","BAW","AFR","DLH","KLM",
    "VIR","UAE","ELY","EIN","QXE","ENY","PDT"
)

$Upstream  = "https://raw.githubusercontent.com/sexym0nk3y/airline-logos/main/logos/{0}.png"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$OutPath   = Join-Path (Split-Path -Parent $ScriptDir) "airline_logos.h"
$Transparent = 0x0001
$AlphaThreshold = 128
$LogoSize = 16   # 16×16 fits next to size-2 airline name on the flight card

Write-Host "Output: $OutPath"

# --- Helpers --------------------------------------------------------------
function ConvertTo-Rgb565([int]$r, [int]$g, [int]$b) {
    $v = ((($r -band 0xF8) -shl 8) -bor (($g -band 0xFC) -shl 3) -bor ($b -shr 3))
    if ($v -eq 0x0001) { $v = 0x0002 }
    return $v
}

function Get-LogoPixels {
    param([byte[]] $PngBytes, [int] $Size)
    $ms = New-Object System.IO.MemoryStream(,$PngBytes)
    $src = [System.Drawing.Image]::FromStream($ms)
    $bmp = New-Object System.Drawing.Bitmap $Size, $Size
    $gfx = [System.Drawing.Graphics]::FromImage($bmp)
    $gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $gfx.SmoothingMode     = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $gfx.PixelOffsetMode   = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    $gfx.Clear([System.Drawing.Color]::Transparent)
    $gfx.DrawImage($src, 0, 0, $Size, $Size)
    $gfx.Dispose()
    $out = New-Object 'System.Collections.Generic.List[int]' ($Size * $Size)
    for ($y = 0; $y -lt $Size; $y++) {
        for ($x = 0; $x -lt $Size; $x++) {
            $c = $bmp.GetPixel($x, $y)
            if ($c.A -lt $AlphaThreshold) { $out.Add($Transparent) | Out-Null }
            else { $out.Add((ConvertTo-Rgb565 $c.R $c.G $c.B)) | Out-Null }
        }
    }
    $bmp.Dispose(); $src.Dispose(); $ms.Dispose()
    return ,$out
}

function Get-PngBytes {
    param([string] $Url)
    try {
        $wc = New-Object System.Net.WebClient
        return ,($wc.DownloadData($Url))
    } catch { return $null }
}

# --- Main loop ------------------------------------------------------------
$arrays  = New-Object 'System.Collections.Generic.List[object]'
$index   = New-Object 'System.Collections.Generic.List[object]'
$fetched = 0
$skipped = New-Object 'System.Collections.Generic.List[string]'

Write-Host "`n== Airlines ($($Airlines.Count) total) =="
foreach ($icao in $Airlines) {
    $url = ($Upstream -f $icao)
    $png = Get-PngBytes $url
    if ($null -eq $png) {
        $skipped.Add($icao) | Out-Null
        Write-Host "  ??  $icao  (not in repo)"
        continue
    }
    try {
        $px = Get-LogoPixels $png $LogoSize
    } catch {
        Write-Host "  ! decode failed for $icao"
        $skipped.Add($icao) | Out-Null
        continue
    }
    $name = "LOGO_AIRLINE_${icao}_16"
    $arrays.Add(@{ Name = $name; Pixels = $px; LineW = 16 }) | Out-Null
    $index.Add(@{ Icao = $icao; Name = $name }) | Out-Null
    $fetched++
    Write-Host "  ok  $icao"
}

Write-Host "`nFetched $fetched airlines, skipped $($skipped.Count)"
if ($skipped.Count -gt 0) {
    Write-Host "Skipped (fall back to text-only at runtime):"
    foreach ($s in $skipped) { Write-Host "  $s" }
}

# --- Write header ---------------------------------------------------------
Write-Host "`nWriting $OutPath ..."
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by tools/build_airline_logos.ps1 - do not edit by hand.")
[void]$sb.AppendLine("// Sourced from https://github.com/sexym0nk3y/airline-logos (ICAO-named PNGs).")
[void]$sb.AppendLine("// Personal-use only; airline marks are property of their respective carriers.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <Arduino.h>")
[void]$sb.AppendLine("#include <pgmspace.h>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine(("#define AIRLINE_LOGO_TRANSPARENT 0x{0:X4}" -f $Transparent))
[void]$sb.AppendLine("#define AIRLINE_LOGO_SIZE 16")
[void]$sb.AppendLine("")
foreach ($arr in $arrays) {
    $name = $arr.Name; $pixels = $arr.Pixels; $lineW = $arr.LineW
    [void]$sb.Append("const uint16_t $name[$($pixels.Count)] PROGMEM = {")
    [void]$sb.AppendLine()
    [void]$sb.Append("  ")
    for ($i = 0; $i -lt $pixels.Count; $i++) {
        [void]$sb.Append(("0x{0:X4}" -f $pixels[$i]))
        if ($i -ne $pixels.Count - 1) {
            [void]$sb.Append(",")
            if ((($i + 1) % $lineW) -eq 0) { [void]$sb.AppendLine(); [void]$sb.Append("  ") }
            else { [void]$sb.Append(" ") }
        }
    }
    [void]$sb.AppendLine(); [void]$sb.AppendLine("};"); [void]$sb.AppendLine()
}
[void]$sb.AppendLine("struct AirlineLogoEntry { const char* icao; const uint16_t* px16; };")
[void]$sb.AppendLine(("const int AIRLINE_LOGO_COUNT = {0};" -f $index.Count))
[void]$sb.AppendLine("const AirlineLogoEntry AIRLINE_LOGOS[AIRLINE_LOGO_COUNT] = {")
foreach ($e in $index) {
    [void]$sb.AppendLine(('  {{ "{0}", {1} }},' -f $e.Icao, $e.Name))
}
[void]$sb.AppendLine("};")
[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

$flashKb = ($fetched * $LogoSize * $LogoSize * 2) / 1024
Write-Host ("`nDone. Approx flash use: {0:N1} KB in PROGMEM." -f $flashKb)
Write-Host "Now re-flash the .ino from the Arduino IDE."
