# =====================================================================
# build_weather_icons.ps1 — downloads OpenWeatherMap's free condition
# icons (the same set the API returns codes for), resizes them, and
# emits ../weather_icons.h with two sizes:
#   * 16×16 — used in the forecast row of the weather card
#   * 24×24 — used as the headline "now" icon
#
# OWM publishes the icons under https://openweathermap.org/img/wn/{code}@4x.png
# (200×200 PNG with transparent background). 18 codes total cover every
# condition OWM reports.
#
# Run from this folder:
#     powershell -ExecutionPolicy Bypass -File .\build_weather_icons.ps1
# =====================================================================

Add-Type -AssemblyName System.Drawing

$Codes = @(
    "01d","01n",   # clear sky
    "02d","02n",   # few clouds
    "03d","03n",   # scattered clouds
    "04d","04n",   # broken clouds / overcast
    "09d","09n",   # shower rain
    "10d","10n",   # rain
    "11d","11n",   # thunderstorm
    "13d","13n",   # snow
    "50d","50n"    # mist / fog
)

$Upstream  = "https://openweathermap.org/img/wn/{0}@4x.png"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$OutPath   = Join-Path (Split-Path -Parent $ScriptDir) "weather_icons.h"
$Transparent = 0x0001
$AlphaThreshold = 80     # OWM icons have soft edges — be slightly more lenient

Write-Host "Output: $OutPath"

function ConvertTo-Rgb565([int]$r, [int]$g, [int]$b) {
    $v = ((($r -band 0xF8) -shl 8) -bor (($g -band 0xFC) -shl 3) -bor ($b -shr 3))
    if ($v -eq 0x0001) { $v = 0x0002 }
    return $v
}

function Get-IconPixels {
    param([byte[]] $PngBytes, [int] $Size)
    $ms = New-Object System.IO.MemoryStream(,$PngBytes)
    $src = [System.Drawing.Image]::FromStream($ms)
    $bmp = New-Object System.Drawing.Bitmap $Size, $Size
    $gfx = [System.Drawing.Graphics]::FromImage($bmp)
    $gfx.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
    $gfx.SmoothingMode     = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
    $gfx.PixelOffsetMode   = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
    $gfx.Clear([System.Drawing.Color]::Transparent)
    $gfx.DrawImage($src, 0, 0, $Size, $Size)
    $gfx.Dispose()
    $out = New-Object 'System.Collections.Generic.List[int]' ($Size * $Size)
    for ($y = 0; $y -lt $Size; $y++) {
        for ($x = 0; $x -lt $Size; $x++) {
            $c = $bmp.GetPixel($x, $y)
            if ($c.A -lt $AlphaThreshold) { $out.Add($Transparent) | Out-Null }
            else { $out.Add((ConvertTo-Rgb565 $c.R $c.G $c.B)) | Out-Null }
        }
    }
    $bmp.Dispose(); $src.Dispose(); $ms.Dispose()
    return ,$out
}

function Get-PngBytes {
    param([string] $Url)
    try {
        $wc = New-Object System.Net.WebClient
        return ,($wc.DownloadData($Url))
    } catch { return $null }
}

$arrays  = New-Object 'System.Collections.Generic.List[object]'
$index   = New-Object 'System.Collections.Generic.List[object]'
$fetched = 0
$skipped = New-Object 'System.Collections.Generic.List[string]'

Write-Host "`n== Weather icons ($($Codes.Count) codes) =="
foreach ($code in $Codes) {
    $url = ($Upstream -f $code)
    $png = Get-PngBytes $url
    if ($null -eq $png) {
        $skipped.Add($code) | Out-Null
        Write-Host "  ??  $code  (404)"
        continue
    }
    try {
        $px16 = Get-IconPixels $png 16
        $px24 = Get-IconPixels $png 24
    } catch {
        Write-Host "  ! decode failed for $code"
        $skipped.Add($code) | Out-Null
        continue
    }
    $safe = $code   # already safe (3 chars, digits + d/n)
    $n16 = "WX_${safe}_16"
    $n24 = "WX_${safe}_24"
    $arrays.Add(@{ Name = $n16; Pixels = $px16; LineW = 16 }) | Out-Null
    $arrays.Add(@{ Name = $n24; Pixels = $px24; LineW = 24 }) | Out-Null
    $index.Add(@{ Code = $code; N16 = $n16; N24 = $n24 }) | Out-Null
    $fetched++
    Write-Host "  ok  $code"
}

Write-Host "`nFetched $fetched icons, skipped $($skipped.Count)"

Write-Host "`nWriting $OutPath ..."
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// AUTO-GENERATED by tools/build_weather_icons.ps1 - do not edit by hand.")
[void]$sb.AppendLine("// Sourced from openweathermap.org/img/wn/{code}@4x.png.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <Arduino.h>")
[void]$sb.AppendLine("#include <pgmspace.h>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine(("#define WX_ICON_TRANSPARENT 0x{0:X4}" -f $Transparent))
[void]$sb.AppendLine("#define WX_ICON_SIZE_16 16")
[void]$sb.AppendLine("#define WX_ICON_SIZE_24 24")
[void]$sb.AppendLine("")
foreach ($arr in $arrays) {
    $name = $arr.Name; $pixels = $arr.Pixels; $lineW = $arr.LineW
    [void]$sb.Append("const uint16_t $name[$($pixels.Count)] PROGMEM = {")
    [void]$sb.AppendLine()
    [void]$sb.Append("  ")
    for ($i = 0; $i -lt $pixels.Count; $i++) {
        [void]$sb.Append(("0x{0:X4}" -f $pixels[$i]))
        if ($i -ne $pixels.Count - 1) {
            [void]$sb.Append(",")
            if ((($i + 1) % $lineW) -eq 0) { [void]$sb.AppendLine(); [void]$sb.Append("  ") }
            else { [void]$sb.Append(" ") }
        }
    }
    [void]$sb.AppendLine(); [void]$sb.AppendLine("};"); [void]$sb.AppendLine()
}
[void]$sb.AppendLine("struct WxIconEntry { const char* code; const uint16_t* px16; const uint16_t* px24; };")
[void]$sb.AppendLine(("const int WX_ICON_COUNT = {0};" -f $index.Count))
[void]$sb.AppendLine("const WxIconEntry WX_ICONS[WX_ICON_COUNT] = {")
foreach ($e in $index) {
    [void]$sb.AppendLine(('  {{ "{0}", {1}, {2} }},' -f $e.Code, $e.N16, $e.N24))
}
[void]$sb.AppendLine("};")
[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

$flashKb = ($fetched * (16*16 + 24*24) * 2) / 1024
Write-Host ("`nDone. Approx flash use: {0:N1} KB in PROGMEM." -f $flashKb)
Write-Host "Now re-flash the .ino from the Arduino IDE."
